// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/draw-drill.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/data/cards.ts
var CATEGORY_ORDER = [
  "time",
  "distance",
  "startPosition",
  "target",
  "courseOfFire"
];
function timeCard(seconds) {
  return {
    id: `time-${seconds}`,
    category: "time",
    label: `${seconds} Seconds`,
    parSeconds: seconds,
    qty: 4
  };
}
function distanceCard(yards) {
  return {
    id: `distance-${yards}`,
    category: "distance",
    label: `${yards} Yards`,
    qty: 4
  };
}
var TIME_CARDS = [2, 3, 4, 5, 6].map(timeCard);
var DISTANCE_CARDS = [2, 5, 7, 10, 12].map(
  distanceCard
);
var START_POSITION_CARDS = [
  { id: "sp-hands-at-sides", label: "Holstered, Hands at Sides" },
  { id: "sp-low-ready", label: "Low Ready" },
  { id: "sp-180-turn", label: "Holstered, 180\xB0 Turn" },
  { id: "sp-wrists-above-shoulders", label: "Holstered, Wrists Above Shoulders" },
  { id: "sp-kneeling-wrists-above-shoulders", label: "Holstered, Kneeling, Wrists Above Shoulders" },
  { id: "sp-low-ready-empty-gun", label: "Low Ready, Empty Gun" }
].map((c) => ({ ...c, category: "startPosition", qty: 4 }));
var TARGET_CARDS = [
  { id: "tg-1-a-zone", label: "1 USPSA A-Zone", detail: '6"x11"' },
  { id: "tg-3-a-zone-3yd", label: "3 USPSA A-Zone", detail: '6"x11", 3 yard spacing' },
  { id: "tg-1-head-box", label: "1 USPSA Head Box", detail: '2"x4"' },
  { id: "tg-2-a-zone-5yd", label: "2 USPSA A-Zone", detail: '6"x11", 5 yard spacing' },
  { id: "tg-2-a-zone-15yd", label: "2 USPSA A-Zone", detail: '6"x11", 15 yard spacing' },
  { id: "tg-2-head-box-7yd", label: "2 USPSA Head Box", detail: '2"x4", spaced 7 yards' }
].map((c) => ({ ...c, category: "target", qty: 4 }));
var COURSE_OF_FIRE_CARDS = [
  { id: "cof-2-reload-after-first", label: "2 Shots on Each Target", detail: "Reload after first shot" },
  { id: "cof-3-each-target", label: "3 Rounds Each Target" },
  { id: "cof-failure-drill", label: "Failure Drill on Each Target", detail: "2 body, 1 head" },
  { id: "cof-1-repeat-3x", label: "1 Round Each Target, Then Repeat", detail: "3 times" },
  { id: "cof-2-strong-hand", label: "2 Rounds Each Target", detail: "Strong hand" },
  { id: "cof-1-each-target", label: "1 Round Each Target" }
].map((c) => ({ ...c, category: "courseOfFire", qty: 4 }));
var CATEGORY_DECKS = {
  time: TIME_CARDS,
  distance: DISTANCE_CARDS,
  startPosition: START_POSITION_CARDS,
  target: TARGET_CARDS,
  courseOfFire: COURSE_OF_FIRE_CARDS
};

// src/lib/mcp/tools/draw-drill.ts
function pick(cards) {
  return cards[Math.floor(Math.random() * cards.length)];
}
var draw_drill_default = defineTool({
  name: "draw_drill",
  title: "Draw a random drill",
  description: "Draw a random Range Roulette training drill: one card each for time, distance, start position, target, and course of fire.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: () => {
    const drill = Object.fromEntries(
      CATEGORY_ORDER.map((cat) => {
        const card3 = pick(CATEGORY_DECKS[cat]);
        return [cat, { cardId: card3.id, label: card3.label, detail: card3.detail }];
      })
    );
    const parSeconds = CATEGORY_DECKS.time.find((c) => c.id === drill.time.cardId)?.parSeconds;
    const payload = { ...drill, parSeconds };
    const text = CATEGORY_ORDER.map((cat) => `${cat}: ${drill[cat].label}`).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { drill: payload }
    };
  }
});

// src/lib/mcp/tools/leaderboard.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.112.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/leaderboard.ts
var leaderboard_default = defineTool2({
  name: "get_leaderboard",
  title: "Get the match leaderboard",
  description: "Aggregate wins, losses, and win percentage from recorded Range Roulette matches.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("match_results").select("player_name, player_name_normalized, won");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const tally = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      const cur = tally.get(row.player_name_normalized) ?? {
        name: row.player_name,
        wins: 0,
        losses: 0
      };
      cur.wins += row.won ? 1 : 0;
      cur.losses += row.won ? 0 : 1;
      tally.set(row.player_name_normalized, cur);
    }
    const standings = [...tally.values()].map((e) => ({
      ...e,
      matchesPlayed: e.wins + e.losses,
      winPct: e.wins + e.losses > 0 ? e.wins / (e.wins + e.losses) : 0
    })).sort((a, b) => b.wins - a.wins || b.winPct - a.winPct || a.name.localeCompare(b.name));
    return {
      content: [
        {
          type: "text",
          text: standings.length ? standings.map(
            (s) => `${s.name}: ${s.wins}W-${s.losses}L (${Math.round(s.winPct * 100)}%)`
          ).join("\n") : "No matches recorded yet."
        }
      ],
      structuredContent: { standings }
    };
  }
});

// src/lib/mcp/tools/list-saved-drills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
var list_saved_drills_default = defineTool3({
  name: "list_saved_drills",
  title: "List saved drills",
  description: "List the signed-in user's saved Range Roulette training drills.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("saved_drills").select("id, name, drill, par_seconds, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: rows.length ? rows.map((r) => `${r.name} (par ${r.par_seconds ?? "\u2014"}s)`).join("\n") : "No saved drills yet."
        }
      ],
      structuredContent: { drills: rows }
    };
  }
});

// src/lib/mcp/tools/list-sessions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^4.5.4";
var list_sessions_default = defineTool4({
  name: "list_training_sessions",
  title: "List training sessions",
  description: "List logged training sessions, most recent first. Optionally filter by trainee name.",
  inputSchema: {
    trainee: z.string().optional().describe("Filter to one trainee name."),
    limit: z.number().optional().describe("Maximum rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ trainee, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const capped = Math.min(Math.max(Math.trunc(limit ?? 20), 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("training_sessions").select("id, trainee, logged_at, raw_seconds, zone_misses, complete_misses, final_seconds, saved_drill_name, drill").order("logged_at", { ascending: false }).limit(capped);
    if (trainee) query = query.eq("trainee_normalized", trainee.trim().toLowerCase());
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: rows.length ? rows.map(
            (r) => `${new Date(r.logged_at).toISOString().slice(0, 10)} \u2014 ${r.trainee}: ${r.final_seconds}s (raw ${r.raw_seconds}s)`
          ).join("\n") : "No sessions logged."
        }
      ],
      structuredContent: { sessions: rows }
    };
  }
});

// src/lib/mcp/tools/log-result.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^4.5.4";
var card = z2.object({
  cardId: z2.string(),
  label: z2.string(),
  detail: z2.string().optional()
});
function computeFinalSeconds(rawSeconds, zoneMisses, completeMisses, parSeconds) {
  let total = rawSeconds + zoneMisses * 0.5 + completeMisses * 1;
  if (parSeconds != null && rawSeconds > parSeconds) total += 1;
  return Math.round(total * 100) / 100;
}
var log_result_default = defineTool5({
  name: "log_training_result",
  title: "Log a training result",
  description: "Log a training run for a trainee: raw time plus zone/complete misses. The penalised final time is computed automatically.",
  inputSchema: {
    trainee: z2.string().describe("Trainee name."),
    rawSeconds: z2.number().describe("Raw time on the timer, in seconds."),
    zoneMisses: z2.number().optional().describe("Number of zone misses (default 0)."),
    completeMisses: z2.number().optional().describe("Number of complete misses (default 0)."),
    savedDrillName: z2.string().optional().describe("Name of a saved drill to log against; its snapshot is used."),
    drill: z2.object({
      time: card,
      distance: card,
      startPosition: card,
      target: card,
      courseOfFire: card,
      parSeconds: z2.number().optional()
    }).optional().describe("Drill snapshot, required when savedDrillName is not given.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let drill = input.drill;
    if (input.savedDrillName) {
      const { data: data2, error: error2 } = await supabase.from("saved_drills").select("name, drill").eq("user_id", ctx.getUserId()).eq("name_normalized", input.savedDrillName.trim().toLowerCase()).maybeSingle();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      if (!data2)
        return {
          content: [{ type: "text", text: `No saved drill named "${input.savedDrillName}".` }],
          isError: true
        };
      drill = data2.drill;
    }
    if (!drill)
      return {
        content: [{ type: "text", text: "Provide either savedDrillName or a drill snapshot." }],
        isError: true
      };
    const zoneMisses = input.zoneMisses ?? 0;
    const completeMisses = input.completeMisses ?? 0;
    const finalSeconds = computeFinalSeconds(
      input.rawSeconds,
      zoneMisses,
      completeMisses,
      drill.parSeconds
    );
    const { data, error } = await supabase.from("training_sessions").insert({
      recorded_by: ctx.getUserId(),
      trainee: input.trainee.trim(),
      trainee_normalized: input.trainee.trim().toLowerCase(),
      drill,
      raw_seconds: input.rawSeconds,
      zone_misses: zoneMisses,
      complete_misses: completeMisses,
      final_seconds: finalSeconds,
      ...input.savedDrillName ? { saved_drill_name: input.savedDrillName.trim() } : {}
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${finalSeconds.toFixed(2)}s for ${input.trainee}.` }],
      structuredContent: { session: data, finalSeconds }
    };
  }
});

// src/lib/mcp/tools/save-drill.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^4.5.4";
var card2 = z3.object({
  cardId: z3.string(),
  label: z3.string(),
  detail: z3.string().optional()
});
var save_drill_default = defineTool6({
  name: "save_drill",
  title: "Save a drill",
  description: "Save a Range Roulette drill under a name for the signed-in user. Re-saving the same name overwrites it.",
  inputSchema: {
    name: z3.string().describe("Name for the saved drill."),
    drill: z3.object({
      time: card2,
      distance: card2,
      startPosition: card2,
      target: card2,
      courseOfFire: card2,
      parSeconds: z3.number().optional()
    }).describe("Drill snapshot, e.g. the output of draw_drill.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, drill }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const trimmed = name.trim();
    if (!trimmed)
      return { content: [{ type: "text", text: "Name is required" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("saved_drills").upsert(
      {
        user_id: ctx.getUserId(),
        name: trimmed,
        name_normalized: trimmed.toLowerCase(),
        drill,
        par_seconds: drill.parSeconds ?? null
      },
      { onConflict: "user_id,name_normalized" }
    ).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved drill "${trimmed}".` }],
      structuredContent: { drill: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "obgfbgggozfbkisozkvr";
var mcp_default = defineMcp({
  name: "range-roulette-connect",
  title: "Range Roulette Connect",
  version: "0.1.0",
  instructions: "Tools for Range Roulette, a firearms training and match app. Draw random drills, save drills by name, log training results with penalties, review session history, and read the match leaderboard. All data is scoped to the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [draw_drill_default, list_saved_drills_default, save_drill_default, log_result_default, list_sessions_default, leaderboard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
